export const COLLECTION = 'devices'
export const JOIN_COLLECTION = 'deviceAdmins'
export const PAIRING_COLLECTION = 'pairingClaims'
export const SUB_CONTACTS = 'contacts'
export const SUB_MESSAGES = 'messages'
export const SUB_CONFIG = 'config'
/** Jeden dokument s provozním nastavením tabletu (PIN, SIM, asistent). */
export const CONFIG_DOC_ID = 'main'

export const KEY_ADMIN_PIN = 'admin_pin'
export const KEY_SIM_NUMBER = 'sim_number'
export const KEY_ASSISTANT_NAME = 'assistant_name'
/** Profil seniora (stejný dokument `config/main`). */
export const KEY_SENIOR_FIRST_NAME = 'senior_first_name'
export const KEY_SENIOR_LAST_NAME = 'senior_last_name'
export const KEY_ADDRESS_LINE = 'address_line'

export const KEY_DEVICE_LABEL = 'deviceLabel'
export const KEY_VOLUME_PERCENT = 'volumePercent'
/** Stav tabletu pro správce (zápis z Android klienta). */
export const KEY_BATTERY_PERCENT = 'batteryPercent'
export const KEY_CHARGING = 'charging'
export const KEY_LAST_HEARTBEAT_AT = 'lastHeartbeatAt'
export const KEY_ALERT_MESSAGE = 'alertMessage'
export const KEY_DEVICE_AUTH_UID = 'deviceAuthUid'
export const KEY_PAIRED = 'paired'
export const KEY_PAIRING_CODE = 'pairingCode'
export const KEY_PAIRING_EXPIRES_AT = 'pairingExpiresAt'
export const KEY_NAME = 'name'
export const KEY_PHONE = 'phone'
export const KEY_SORT_ORDER = 'sortOrder'
/** Kontakt označený pro nouzi / Matěje (priorita). */
export const KEY_IS_EMERGENCY = 'is_emergency'
export const KEY_DEVICE_ID = 'deviceId'
export const KEY_UID = 'uid'
export const KEY_ROLE = 'role'
export const KEY_CLAIM_CODE = 'claimCode'
export const KEY_CODE = 'code'
export const KEY_EXPIRES_AT = 'expiresAt'
export const KEY_USED_AT = 'usedAt'
export const KEY_USED_BY_UID = 'usedByUid'

export const KEY_MESSAGE_BODY = 'body'
export const KEY_MESSAGE_CREATED_AT = 'createdAt'
export const KEY_MESSAGE_READ_AT = 'readAt'
export const KEY_SENDER_UID = 'senderUid'
export const KEY_SENDER_DISPLAY_NAME = 'senderDisplayName'
